# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='recommend',
            field=models.CharField(choices=[('Yes', 'Recommend'), ('No', 'Never again')], default='Yes', max_length=3),
            preserve_default=False,
        ),
    ]
